export const Traits = {
    art: 0,
    basketball: 1,
    blockchain: 2,
    bookworm: 3,
    carroms: 4,
    chess: 5,
    cricket: 6,
    dance: 7,
    foodie: 8,
    football: 9,
    gamer: 10,
    hackathons: 11,
    humourous: 12,
    lgbtq: 13,
    movies: 14,
    music: 15,
    photography: 16,
    puzzles: 17,
    traveler: 18,
    weeb: 19,
};
